### ISSUE TITLE
Windows 8 (but not Windows 7 or 10?) compilation fails

### ISSUE THREAD

**Issue by swayson** [bmschmidt/wordVectors#2] opened 2015-10-29 13:21 UTC
Hi there,

I am having trouble installing this on Windows 8 64-bit. I do have Rtools installed as well.

```
> devtools::install_github("bmschmidt/wordVectors")
Downloading GitHub repo bmschmidt/wordVectors@master
Installing wordVectors
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/MotoBot/AppData/Local/Temp/Rtmpq836VL/devtools21f45c5a6f54/bmschmidt-wordVectors-cfd14a5"  \
  --library="C:/Users/MotoBot/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'wordVectors' ...
** libs

*** arch - i386
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.1/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result    -O3 -Wall  -std=gnu99 -mtune=core2 -c tmcn_distance.c -o tmcn_distance.o
In file included from tmcn_distance.c:2:0:
distance.h: In function 'distance':
distance.h:40:3: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:40:3: warning: too many arguments for format [-Wformat-extra-args]
distance.h:41:3: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:41:3: warning: too many arguments for format [-Wformat-extra-args]
distance.h:42:3: warning: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
distance.h:42:19: warning: incompatible implicit declaration of built-in function 'malloc' [enabled by default]
distance.h:45:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:45:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:45:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:45:5: warning: too many arguments for format [-Wformat-extra-args]
distance.h:84:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:84:5: warning: too many arguments for format [-Wformat-extra-args]
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.1/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result    -O3 -Wall  -std=gnu99 -mtune=core2 -c tmcn_word2vec.c -o tmcn_word2vec.o
In file included from tmcn_word2vec.c:3:0:
word2vec.h: In function 'LearnVocabFromTrainFile':
word2vec.h:280:7: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:280:7: warning: format '%c' expects argument of type 'int', but argument 2 has type 'long long int' [-Wformat]
word2vec.h:280:7: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:292:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:292:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:293:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:293:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h: In function 'SaveVocab':
word2vec.h:302:3: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:302:3: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h: In function 'ReadVocab':
word2vec.h:321:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:321:5: warning: format '%c' expects argument of type 'char *', but argument 3 has type 'long long int *' [-Wformat]
word2vec.h:321:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:326:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:326:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:327:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:327:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h: In function 'TrainModelThread':
word2vec.h:367:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
word2vec.h:373:50: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
word2vec.h: In function 'TrainModel':
word2vec.h:549:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:549:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:549:5: warning: too many arguments for format [-Wformat-extra-args]
tmcn_word2vec.c: In function 'tmcn_word2vec':
tmcn_word2vec.c:12:9: warning: assignment makes pointer from integer without a cast [enabled by default]
tmcn_word2vec.c: In function 'TrainModelThread':
word2vec.h:530:1: warning: control reaches end of non-void function [-Wreturn-type]
gcc -m32 -shared -s -static-libgcc -o wordVectors.dll tmp.def tmcn_distance.o tmcn_word2vec.o -pthread -Ld:/RCompile/r-compiling/local/local320/lib/i386 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/PROGRA~1/R/R-32~1.1/bin/i386 -lR
installing to C:/Users/MotoBot/Documents/R/win-library/3.2/wordVectors/libs/i386

*** arch - x64
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.1/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result    -O2 -Wall  -std=gnu99 -mtune=core2 -c tmcn_distance.c -o tmcn_distance.o
In file included from tmcn_distance.c:2:0:
distance.h: In function 'distance':
distance.h:40:3: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:40:3: warning: too many arguments for format [-Wformat-extra-args]
distance.h:41:3: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:41:3: warning: too many arguments for format [-Wformat-extra-args]
distance.h:42:3: warning: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
distance.h:42:19: warning: incompatible implicit declaration of built-in function 'malloc' [enabled by default]
distance.h:45:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:45:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:45:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:45:5: warning: too many arguments for format [-Wformat-extra-args]
distance.h:84:5: warning: unknown conversion type character 'l' in format [-Wformat]
distance.h:84:5: warning: too many arguments for format [-Wformat-extra-args]
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.1/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result    -O2 -Wall  -std=gnu99 -mtune=core2 -c tmcn_word2vec.c -o tmcn_word2vec.o
In file included from tmcn_word2vec.c:3:0:
word2vec.h: In function 'LearnVocabFromTrainFile':
word2vec.h:280:7: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:280:7: warning: format '%c' expects argument of type 'int', but argument 2 has type 'long long int' [-Wformat]
word2vec.h:280:7: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:292:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:292:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:293:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:293:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h: In function 'SaveVocab':
word2vec.h:302:3: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:302:3: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h: In function 'ReadVocab':
word2vec.h:321:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:321:5: warning: format '%c' expects argument of type 'char *', but argument 3 has type 'long long int *' [-Wformat]
word2vec.h:321:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:326:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:326:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h:327:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:327:5: warning: too many arguments for format [-Wformat-extra-args]
word2vec.h: In function 'TrainModel':
word2vec.h:544:84: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
word2vec.h:549:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:549:5: warning: unknown conversion type character 'l' in format [-Wformat]
word2vec.h:549:5: warning: too many arguments for format [-Wformat-extra-args]
tmcn_word2vec.c: In function 'tmcn_word2vec':
tmcn_word2vec.c:12:9: warning: assignment makes pointer from integer without a cast [enabled by default]
tmcn_word2vec.c: In function 'TrainModelThread':
word2vec.h:530:1: warning: control reaches end of non-void function [-Wreturn-type]
C:\Users\MotoBot\AppData\Local\Temp\cc88Kdj9.s: Assembler messages:
C:\Users\MotoBot\AppData\Local\Temp\cc88Kdj9.s:1094: Error: no such instruction: `vfmadd312ss (%rbx),%xmm0,%xmm8'

[... edited out by BMS--dozens of other assembler errors]

make: *** [tmcn_word2vec.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.1/share/make/winshlib.mk" SHLIB="wordVectors.dll" WIN=64 TCLBIN=64 OBJECTS="tmcn_distance.o tmcn_word2vec.o"' had status 2
ERROR: compilation failed for package 'wordVectors'
* removing 'C:/Users/MotoBot/Documents/R/win-library/3.2/wordVectors'
```

My environment:

```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252   
[3] LC_MONETARY=English_South Africa.1252 LC_NUMERIC=C                         
[5] LC_TIME=English_South Africa.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.0.0     R6_2.1.1       magrittr_1.5   tools_3.2.1    curl_0.9.3    
 [6] memoise_0.2.1  stringi_1.0-1  knitr_1.11     stringr_1.0.0  digest_0.6.8  
[11] devtools_1.9.1
```

Any idea how I can fix this?

Thanks

**Comment by bmschmidt** [comment] 2015-10-29 17:33
Hmm, this is slightly above my paygrade. I've heard another account of Windows machines having problem; I have to look for the Windows machine I tested it on to see what's different.

One guess: something about certain windows compilers doesn't allow `long long int`s. I don't have a solution, though.

**Comment by shawngraham** [comment] 2015-10-30 15:50
I'm on a windows 7 machine today, and it installed ok, if that helps.

> platform       x86_64-w64-mingw32  
> arch           x86_64  
> os             mingw32  
> system         x86_64, mingw32  
> status  
> major          3  
> minor          0.3  
> year           2014  
> month          03  
> day            06  
> svn rev        65126  
> language       R  
> version.string R version 3.0.3 (2014-03-06)
> nickname       Warm Puppy

**Comment by bmschmidt** [comment] 2015-10-30 16:10
Maybe it's 7 vs 8 then. The windows machine I tested it on was 7 as well.

**Comment by swayson** [comment] 2015-11-02 05:40
Thanks for the help. I am going to try and install it again on a Windows 7 machine today and will confirm whether that is in fact the case.

**Comment by swayson** [comment] 2015-11-02 13:46
To confirm -- I installed the package on Windows 7 (64-bit) successfully.

**Comment by bmschmidt** [comment] 2015-11-04 19:30
Great! I'm leaving this open as a bug because it should work on Windows 8, in any case.

**Comment by bmschmidt** [comment] 2015-11-04 19:30
I have one report of a successful install on Windows 10.

**Comment by bmschmidt** [comment] 2015-11-06 15:15
If the problem is `long long int` types being defined, this might work here: http://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/4F893862.1060206@users.sourceforge.net/

**Comment by bmschmidt** [comment] 2015-11-06 15:28
Perhaps some more on this issue: 
http://www.thecodingforums.com/threads/long-long-int-and-sscanf-printf.951918/. 

Essentially, it seems like (just for Windows 8??) the mingw bundled version of GCC does not implement "C99" support, instead using a different system for long long integers.

So **if** the problem is these errors, the solution might be to add some incantations to the C headers along those lines.

I'm afraid I'll have trouble fixing this, because

1) I really have no idea what's going on in C, and am just wrapping Jian Li's code with a few more features
2) I don't have access to a Windows 8 machine to test on. (I've been testing on Ubuntu 14.04, OS X 10.9, and Windows 7).

One option would be for people to just use the C code from word2vec in the raw form. But that too, has some problems; I had to change a couple lines to get it to compile on OS X.

**Comment by HansGR** [comment] 2015-11-18 22:36
I ran into the same problem on a Win10 laptop that is upgraded from Windows 8.1.  Interestingly, Rstudio thinks it's a Windows 8 x64 machine:

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] devtools_1.9.1
> 
> loaded via a namespace (and not attached):
> [1] httr_1.0.0    R6_2.1.1      magrittr_1.5  tools_3.2.2   curl_0.9.3    memoise_0.2.1 stringi_1.0-1  stringr_1.0.0
> [9] digest_0.6.8

**Comment by alexlifshitz** [comment] 2016-04-17 05:18
I am getting exactly the same "ERROR: compilation failed for package 'wordVectors'" on Window 7 machine.
Here is my session info:

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.10.0

loaded via a namespace (and not attached):
[1] httr_1.1.0         R6_2.1.2           rsconnect_0.4.1.11 tools_3.2.3        withr_1.0.1        curl_0.9.5         memoise_1.0.0      git2r_0.13.1       digest_0.6.9      

```

Any idea what goes wrong?
Thanks!

**Comment by bmschmidt** [comment] 2016-04-17 19:23
Hmm. The only difference I see between this and the Windows 7 builds running above is that you have more 64-bit stuff in your header.

I have no guarantees anything will work, but possibly updating mingw further would work; or _downgrading_ it to a 32 bit version from your existing 64bit version. But unfortunately, I'm really waiting for someone who knows both windows and C to suggest the best option.

**Comment by ghost** [comment] 2016-06-24 15:18
I had this issue (Win10, 64bit, RStudio) and found it was I was using an older version of R.  Upgrading to the (as of this post) current version of 3.3.1 meant I didn't get the compile error anymore.

**Comment by BruceZhaoR** [comment] 2016-08-03 09:22
## Success  in Win 8.1 now.

I encountered this problem before，but now it works.
Here is the record:

``` r
> devtools::install_github("bmschmidt/wordVectors")
Downloading GitHub repo bmschmidt/wordVectors@master
from URL https://api.github.com/repos/bmschmidt/wordVectors/zipball/master
Installing wordVectors
"E:/R/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/BruceZhao/AppData/Local/Temp/Rtmpyc6tGw/devtools3a431783bbd/bmschmidt-wordVectors-6cfb717"  \
  --library="E:/R/R-3.3.1/library" --install-tests 

* installing *source* package 'wordVectors' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"E:/R/R-3.3.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -w   -O2 -Wall  -std=gnu99 -mtune=core2 -c tmcn_distance.c -o tmcn_distance.o
c:/Rtools/mingw_64/bin/gcc  -I"E:/R/R-3.3.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -w   -O2 -Wall  -std=gnu99 -mtune=core2 -c tmcn_word2vec.c -o tmcn_word2vec.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o wordVectors.dll tmp.def tmcn_distance.o tmcn_word2vec.o -pthread -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LE:/R/R-3.3.1/bin/x64 -lR
installing to E:/R/R-3.3.1/library/wordVectors/libs/x64
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Creating a generic function for 'plot' from package 'graphics' in package 'wordVectors'
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (wordVectors)
> library(wordVectors)
> devtools::session_info()
Session info -----------------------------------------------------------------------
 setting  value                         
 version  R version 3.3.1 (2016-06-21)  
 system   x86_64, mingw32               
 ui       RStudio (0.99.1251)           
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 tz       Asia/Shanghai                 
 date     2016-08-03                    

Packages ---------------------------------------------------------------------------
 package     * version date       source                                
 curl          1.1     2016-07-26 CRAN (R 3.3.1)                        
 devtools      1.12.0  2016-06-24 CRAN (R 3.3.1)                        
 digest        0.6.9   2016-01-08 CRAN (R 3.2.3)                        
 fortunes      1.5-3   2016-05-20 CRAN (R 3.3.0)                        
 git2r         0.15.0  2016-05-11 CRAN (R 3.3.0)                        
 httr          1.2.1   2016-07-03 CRAN (R 3.3.1)                        
 memoise       1.0.0   2016-01-29 CRAN (R 3.2.3)                        
 R6            2.1.2   2016-01-26 CRAN (R 3.2.3)                        
 rstudioapi    0.6     2016-06-27 CRAN (R 3.3.0)                        
 withr         1.0.2   2016-06-20 CRAN (R 3.3.0)                        
 wordVectors * 1.0     2016-08-03 Github (bmschmidt/wordVectors@6cfb717)

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
```

**Comment by bmschmidt** [comment] 2016-08-04 14:42
Super, thanks for the reports. I'm going to provisionally say that the last commit seems to have solved this and close the issue. If anyone else encounters it, we can reopen.

**Closed as completed by bmschmidt** 2016-08-04 14:42 UTC

**Comment by Surya1987** [comment] 2017-09-21 06:25
Though the wordvectors got installed in windows 10 still It is throwing a fatal error in R studio and R is restarting when I am using train_word2vec. Kindly suggest what is the issue

**Comment by kunal368** [comment] 2018-06-11 19:27
I am not being able to install the package on WINDOWS 8 machine. Getting this error:

>devtools::install_github("bmschmidt/wordVectors")
Downloading GitHub repo bmschmidt/wordVectors@master
from URL https://api.github.com/repos/bmschmidt/wordVectors/zipball/master
Installing wordVectors
"C:/PROGRA~1/MIE74D~1/RSERVE~1/R_SERVER/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/kunal.agarwal/AppData/Local/Temp/3/RtmpsnYxOR/devtools23e86cc8249c/bmschmidt-wordVectors-7f1914c"  \
  --library="C:/Users/kunal.agarwal/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'wordVectors' ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unable to identify current timezone 'C':
please set environment variable 'TZ'
** libs
C:/PROGRA~1/MIE74D~1/RSERVE~1/R_SERVER/etc/x64/Makeconf:230: warning: overriding commands for target `.m.o'
C:/PROGRA~1/MIE74D~1/RSERVE~1/R_SERVER/etc/x64/Makeconf:223: warning: ignoring old commands for target `.m.o'
C:/RBuildTools/3.4/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MIE74D~1/RSERVE~1/R_SERVER/include" -DNDEBUG     -I"C:/swarm/workspace/External-R-3.4.1/vendor/extsoft/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -w   -O2 -Wall  -std=gnu99 -mtune=core2 -c tmcn_word2vec.c -o tmcn_word2vec.o
C:/RBuildTools/3.4/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MIE74D~1/RSERVE~1/R_SERVER/include" -DNDEBUG     -I"C:/swarm/workspace/External-R-3.4.1/vendor/extsoft/include"  -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -w   -O2 -Wall  -std=gnu99 -mtune=core2 -c word2phrase.c -o word2phrase.o
C:/RBuildTools/3.4/mingw_64/bin/gcc -m64 -shared -s -static-libgcc -o wordVectors.dll tmp.def tmcn_word2vec.o word2phrase.o -pthread -LC:/swarm/workspace/External-R-3.4.1/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.4.1/vendor/extsoft/lib -LC:/PROGRA~1/MIE74D~1/RSERVE~1/R_SERVER/bin/x64 -lR
: symbol not defineddToVocab
: symbol not defineddToVocab1
: symbol not defined
: symbol not defineder_word2vec
: symbol not definedBinaryTree
: symbol not defineddHash
: symbol not defineddHash1
: symbol not definedt
: symbol not definedigramTable
: symbol not definedocabFromTrainFile
: symbol not definedocabFromTrainFile1
: symbol not definedcab
: symbol not definedrd
: symbol not definedrd1
: symbol not definedrd1Index1
: symbol not definedrdIndex
: symbol not definedVocab
: symbol not definedVocab1
: symbol not definedcab
: symbol not definedVocab
: symbol not definedVocab1
: symbol not definedcab
: symbol not definedcab1
: symbol not definedodel
: symbol not definedodel1
: symbol not definedodelThread
: symbol not definedompare
: symbol not definedompare1
: symbol not defined
: symbol not defined
: symbol not defined
: symbol not defineds
: symbol not definedmode
: symbol not definedmode1
: symbol not definedle
: symbol not definedize
: symbol not defined
: symbol not defined
: symbol not defined_size
: symbol not definedunt
: symbol not definedunt1
: symbol not definedduce
: symbol not definedduce1
: symbol not definedve
: symbol not definedandom
: symbol not definedreads
: symbol not defined_file
: symbol not defined_file1
: symbol not definedocab_file
: symbol not defined
: symbol not definedocab_file
: symbol not defined
: symbol not definedng_alpha
: symbol not defined
: symbol not defined
: symbol not definedg
: symbol not defined
: symbol not definedsize
: symbol not definedold1
: symbol not definedord2vec
: symbol not definedfile
: symbol not definedfile1
: symbol not definedwords
: symbol not definedwords1
: symbol not defined
: symbol not definedhash
: symbol not definedhash1
: symbol not definedhash1_size1
: symbol not definedhash_size
: symbol not definedmax_size
: symbol not definedmax_size1
: symbol not definedsize
: symbol not definedsize1
: symbol not defined
: symbol not definedhrase
: symbol not definedount_actual
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'wordVectors'
* removing 'C:/Users/kunal.agarwal/Documents/R/win-library/3.4/wordVectors'
Installation failed: Command failed (1)

> session_info()
Session info --------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  English_United States.1252  
 tz       unknown                     
 date     2018-06-11
